#!/bin/bash
#Use this file to run commands after the build.

##You should leave the following block of code in your repository to allow GitHub integration.
#Since I installed jupyterlab-git, I wanted to rebuild jupyterlab so I run:
jupyter lab build
##